### ISSUE TITLE
Poslať poznámky zo stretnutia so zadávateľom zadávateľovi

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/vlaky#1]
Prosím poslať poznámky zo stretnutia so zadávateľom všetkým zadávateľom na skontrolovanie a doplnenie, možno pridať hneď aj otázky, ktoré v analýze zatiaľ vyplynú.

**Comment by jakino22** [comment]
Prva cast poznamok zo stretnutia:

[poznamky01.txt](https://github.com/TIS2023-FMFI/vlaky/files/12874168/poznamky01.txt)



[tabuľa.xlsx](https://github.com/TIS2023-FMFI/vlaky/files/12874171/tabula.xlsx)





![Image](https://github.com/TIS2023-FMFI/vlaky/assets/146848411/0e3be7a3-4355-45e7-b0a8-6d179bf8fa9d)

**Comment by Pia669** [comment]
Druha cast poznamok zo stretnutia:

[poznamky02.txt](https://github.com/TIS2023-FMFI/vlaky/files/12874365/poznamky02.txt)

**Comment by dedinside1337** [comment]
Tretia cast poznamok zo stretnutia:
[poznamky03.txt](https://github.com/TIS2023-FMFI/vlaky/files/12883705/poznamky03.txt)

**Comment by adrkoc** [comment]
posledná časť poznámok:

[poznamky04.txt](https://github.com/TIS2023-FMFI/vlaky/files/12890633/poznamky04.txt)

**Comment by adrkoc** [comment]
posielam zhrnutie všetkých poznámok, sporadicky uložené jednotlivé body aby to dávalo zmysel
[finalne_poznamky.txt](https://github.com/TIS2023-FMFI/vlaky/files/12891844/finalne_poznamky.txt)

je tam spomenutá aj fotka kancelárie a poskytnuté údaje v excel tabuľke, aby v tom nebol chaos tak to posielam znovu 
[tabula.xlsx](https://github.com/TIS2023-FMFI/vlaky/files/12891858/tabula.xlsx)
![tabula_img](https://github.com/TIS2023-FMFI/vlaky/assets/125208707/f9b04419-6891-4ed4-8d59-d158ef5266c9)

**Comment by dedinside1337** [comment]
Posielam finalnu verziu poziadaviek
[finalne_poznamky.txt](https://github.com/TIS2023-FMFI/vlaky/files/12906735/finalne_poznamky.txt)

**Comment by Pia669** [comment]
Otazky zo stretnutia na poslanie zadavatelovy

[otazky_na_zadavatela.txt](https://github.com/TIS2023-FMFI/vlaky/files/12906732/otazky_na_zadavatela.txt)

**Comment by jakino22** [comment]
Poznámky, nahrávka aj otázky som odoslal zadávateľovi
