### ISSUE TITLE
Vytvorit UML component diagram

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#10]

**Comment by dedinside1337** [comment]
predverzia component diagramu
![Untitled](https://github.com/TIS2023-FMFI/vlaky/assets/55761731/ed922ea6-f344-4d95-ba61-b3be157be0f0)

**Comment by dedinside1337** [comment]
druha verzia component diagramu(bez db)

![Image](https://github.com/TIS2023-FMFI/vlaky/assets/55761731/df77be64-5897-4e6d-a30b-69f1dae8a6f7)

**Comment by dedinside1337** [comment]
Posledna verzia component diagramu(mozu byt zmeny)
![Image](https://github.com/TIS2023-FMFI/vlaky/assets/55761731/8aa71c48-2063-44c9-81b3-c584d587e730)

**Comment by dedinside1337** [comment]
trochu upraveny diagram

![Image](https://github.com/TIS2023-FMFI/vlaky/assets/55761731/784add0d-60e3-4c4d-b4c7-26375de54eae)
