### ISSUE TITLE
finalna dokumentacia (technicka dokumentacia)

### ISSUE THREAD

**Issue by adrkoc** [TIS2023-FMFI/vlaky#109]
- spojenie dokumetov návrhu a katalógu požiadaviek 
- pridanie príručky o rôznych používateľoch 
- aktualizovať component diagram
- aktualizovať katalog požiadaviek

**Comment by dedinside1337** [comment]
popis component diagramu

[Moduly.txt](https://github.com/TIS2023-FMFI/vlaky/files/14270352/Moduly.txt)

**Comment by adrkoc** [comment]
katalog požiadaviek bol zmenený a spojený s návrhom, ktorá bola tiež editovaná, jednotlivé privilégia popísané, component diagram updatnutý aj jeho moduly
