### ISSUE TITLE
Vytvorit UML class diagram

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#11]

**Comment by jakino22** [comment]
prva verzia diagramu, este bude prediskutovana na stretnuti



![Image](https://github.com/TIS2023-FMFI/vlaky/assets/146848411/94e1493b-82c6-4f91-9c02-51bbc2e40ad2)

**Comment by jakino22** [comment]
na základe diskusie vytvorený nový triedny diagram:



![Image](https://github.com/TIS2023-FMFI/vlaky/assets/146848411/7839c4b2-b234-48dd-b1d9-a77cf0f3c4c5)

**Comment by jakino22** [comment]
Budeme mať dva typy používateľov - admin a user. Na základe getType() sa im určia privilégiá.
Trieda Train reprezentuje samotný vlak. Každý vlak môže mať jeden template, ale na viacero vlakov môže byť použitý rovnaký template. Vagón je agregácia Train, teda vlak sa v skratke skladá z vozňov. Aj vlak aj vagón môžu mať max jednu poznámka, a rovnaká poznámka nemôže patriť rôznym objaktom. Blackboard note je odvodená od Note. Je to poznámka ktorá sa nachádza špecificky na tabuli a nikde inde. Je agragáciou Blackboard, ktorá reprezentuje tabuľu poznámok.
