### ISSUE TITLE
Zbytok casti 3.D (Navrhu)

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#13]
zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky

**Comment by dedinside1337** [comment]
Popis component diagramu(rozdelenie na moduly)

[Moduly.txt](https://github.com/TIS2023-FMFI/vlaky/files/13465211/Moduly.txt)
