### ISSUE TITLE
otázky pre zadávateľa a IT

### ISSUE THREAD

**Issue by adrkoc** [TIS2023-FMFI/vlaky#18]
každý z nás spíše otázky, ktoré sa chceme pýtať na stretnutí so zadávateľom, môžu byť aj otázky na IT, pošlú sa vopred

**Comment by Pia669** [comment]
Ci zadavatelia dovalia nainstalovat dotnet package?
Aky maju server (Apache, Nginx, ...)?
Ci a aku maju DB (MySql, MariaDB,...)?
Ak nemaju ci dovolia nainstalivat?

**Comment by jakino22** [comment]
Ako bude zabezpečený server? Mohli by sme k nemu dostať bližšie informácie? Akú rolu tu hrá Sharepoint? Mohli by sme k nemu dostať bližšiu dokumentáciu? Nemáme s ním veľa skúseností. (Toto je skôr otázka na technika)
Je maximálna dĺžka iná od reálnej dĺžky? Majú byť zobrazované oba parametre?  Na čo slúži maximálna dĺžka? Má každý vlak mať maximálnu a reálnu dĺžku? Majú byť tieto parametre meniteľné?
Ako má fungovať náhľad vyexpedovných vlakov za určité obdobie? 
 V akom formáte by mali byť informácie ktoré budú exportované do power BI? Mohli by sme dostať nejakú šablónu a ukážku ako to funguje?

Ako presne funguje Váš sharepoint? Aké technológie sú na ňom prístupné? Bude na ňom možné prevádzkovať ASP.net? Aké typy serverov môžme použiť?

Ako presne má fungovať export do PowerBI? Máte nejaký template na to, ktoré dáta máme exportovať?

**Comment by adrkoc** [comment]
ja mám hlavne otázky ohľadom UI, sú spísané v dokumente, ktorý budeme prezentovať zadávateľovi

hlavné veci: 
- prihlasovanie a obnovovanie hesla na stránke
- koľko priorít a ich výzor, teda zmena farby a podobne
- pri rozvrhu vlakov, zobrazovať rozvrh od aktuálneho dátumu alebo od posledného nevybaveného vlaku (vybavený je expedovaný alebo zrušený)
- farby stavov vlakov

**Comment by adrkoc** [comment]
UI poslať zadávateľovi, či je spokojný so zmenami


[používateľsky návrh.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13464861/pouzivatelsky.navrh.pdf)


treba sa opýtať ohľadom registrácie, registrovať sa bude používateľ na stránke a čaká kým mu administrátor potvrdí prístup na stránku, alebo účet vytvorí administrátor a poskytne info použivateľovi, alebo ako to chcú
