### ISSUE TITLE
Zmeny Navrhu

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#19]
Tuto pridavajte akekolvek odklonenia od navrhu, aby sme vedely opravit Navrch na konci.

**Comment by Pia669** [comment]
prava uzivatelov:
8 bit int: 87654321
1. sprava uzivatelov
2. sprava poznamok
3. vytvarenie sablon
4. vytvaranie a zmeny vlakov a vagonov
5. poznamky ku vlakom a vagonom
6. poznamky do tabule

**Comment by jakino22** [comment]
7 bit dajme pristup k stranke ako takej, teda ci sa uzivatel bude vediet prihlasit

**Comment by jakino22** [comment]
takisto do grafickeho navrhu by som dal dve tlacitka na account manager, zmenit privilegia a odstranit pouzivatela, pride mi to prkatickejsie ako si ich selectovat checkboxmi, radsej riesme tie accounts individualne

**Comment by Pia669** [comment]
zmeny v navrhu logu

**Comment by adrkoc** [comment]
zmeny urobené v návrhu, done
