### ISSUE TITLE
Podla kompletnych poznamok vytvorit nestrukturovany zoznam poziadaviek

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#2]

**Comment by jakino22** [comment]
perspektíva systému, funkcie systému a charakteristika používateľov

[Perspektíva systému.docx](https://github.com/TIS2023-FMFI/vlaky/files/12910254/Perspektiva.systemu.docx)

**Comment by Pia669** [comment]
kapitola 3 z katalogu

[Katalog CH3.docx](https://github.com/TIS2023-FMFI/vlaky/files/12910520/Katalog.CH3.docx)

**Comment by dedinside1337** [comment]
2.4. vseobecne obmedzenie, 2.5. predpoklady a zavislosti
[vseobecne obmedzenie, predpoklady a zavislosti.docx](https://github.com/TIS2023-FMFI/vlaky/files/12917812/vseobecne.obmedzenie.predpoklady.a.zavislosti.docx)
