### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#21]

**Comment by dedinside1337** [comment]
[Rozvrh, plánovanie vlakov a zmena stavu.txt](https://github.com/TIS2023-FMFI/vlaky/files/13453353/Rozvrh.planovanie.vlakov.a.zmena.stavu.txt)

**Comment by dedinside1337** [comment]
(upravene)

[Rozvrh, plánovanie vlakov a zmena stavu.txt](https://github.com/TIS2023-FMFI/vlaky/files/13559230/Rozvrh.planovanie.vlakov.a.zmena.stavu.txt)

**Comment by adrkoc** [comment]
[Vytvorenie, zmena, odstráňovanie poznámok všetkými používateľmi.txt](https://github.com/TIS2023-FMFI/vlaky/files/13560566/Vytvorenie.zmena.odstranovanie.poznamok.vsetkymi.pouzivatelmi.txt)
