### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#23]
- [x] .css
- [x] Kostra (hlavicka, nav, peta)
- [x] Index (nastenka) (P1, P2, S7)
- [x] Login (P1, P2, S3)
- [x] Rozvrch (P1, P2, S4)
- [x] Vlak (P1, P2, S4, S6)
- [x] Historia (P1, P2, S4)
- [x] Admin (P1, P2, S3)
- [x] Change (P1, P2, S3, S8)
- [x] Forbidden
- [x] TempMang

**Comment by adrkoc** [comment]
done
