### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#25]
- [x] DbConnectionService
- [x] SQLService (S1)
- [x] UserManagerService (S2, M2)
- [x] TrainManagerService (S2, M3)
- [x] TemplateManagerService (S2, M4)
- [x] WagonManagerService (S2, M5)
- [x] NotesManagerService (S2, M6)
- [ ] UserChangesManagerService (S2, M2, M1)

**Comment by jakino22** [comment]
UserChangesManagerService - nieje tato funkcionalita uz v jednotlivych classes?
