### ISSUE TITLE
Podla zoznamu poziadaviek vytvorit katalog poziadaviek

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#3]
Najneskor do pondelka 16.10. vecer

**Comment by adrkoc** [comment]
vyrvorený predbežný katalóg požiadaviek

[docs/Katalóg požiadaviek.pdf](https://github.com/TIS2023-FMFI/vlaky/blob/main/docs/Katal%C3%B3g%20po%C5%BEiadaviek.pdf)

treba prekonzultovať s profesorom, prípadne pridáme ďalšie požiadavky alebo mźmeníme iné časti

**Comment by pavelpetrovic** [comment]
drobne postrehy:
 - ucel 1.1  pre koho je dokument je urceny mozete explicitne uviest
 - 1.2. vlaky - naozaj vlaky? vsetky vlaky?
 - colny status vystelit hned v slovniku
 - upresnit tie procesy na konci zameru; požadovaných informácií = nic nehovoriaca fraza; správu vlakov = ?
 - návrh vlaku => ?
 - aj ostatne pojmy prosim upresnit
 - do odkazov pridat pomenovanie vsetkych dokumentov, obrazkov, cohokolvek, co ste dostali k dispozicii
 - 1.5. v ktorej kap. co
 - 2.1. je tu priestor pre lepsie zasadenie systemu do kontextu (1-2 vety) ale ak budete mat cas...
 -typy a sablony (aby bolo jasne, ze myslite to iste - bud ten isty nazov, alebo niekde vysvetlit, ze je to to iste)
 - prosim cele 2.2. dokladne vycistit a vyladit
 - citame cast 3:
 - zdoraznit, ze zakladne sa nevztahuju na funkcionalitu
 - Softvér obsahuje plánovač => vyviedlo ma z miery
 - plánujú vlaky na konkrétny dátum  => uz su asi naplanovane ale iba maju moznost do systemu zaevidovat cas a datum odchodov evidovanych vlakov (predtym by som ale chcel vediet, ze vobec nejake vlaky eviduju)
 - uviest presne typy pre vsetky udaje
 - co si viem zobrazit a ako, co sa zobrazuje v nahlade
 - vagony?
 - statistiky - prosim rozpisat, "rôznych kritérií," nestaci
 - dát do formátu Power BI. => co sa tym mysli

**Comment by jakino22** [comment]
Na zaklade postrehov upravena cast 2.2 a 2.3

[Perspektíva systému (1).docx](https://github.com/TIS2023-FMFI/vlaky/files/13046029/Perspektiva.systemu.1.docx)

**Comment by jakino22** [comment]
doladene detaily 2.2 a 2.3

[Perspektíva systému (2).docx](https://github.com/TIS2023-FMFI/vlaky/files/13064495/Perspektiva.systemu.2.docx)

**Comment by pavelpetrovic** [comment]
3 Špecifikácia požiadaviek
3.1 Nefunkcionálne požiadavky
3.1.1 Softvér je implementovaný ako webová aplikácia.
3.1.2 Softvér je prístupný z desktopových a mobilných zariadení pomocou webového prehlia-
dača.
3.1.3 Softvér je vybavený grafickým rozhraním pre intuitívne ovládanie.
3.2 Prihlasovanie a užívateľské role
<<3.2.1 Na prácu so softvérom je nutné prihlásiť sa používateľským kontom. Rôzni používatelia
majú rôzne privilégia.
>>3.2.1 Na prácu so softvérom je nutné prihlásiť sa zadaním mena a hesla. 
3.2.2 Administrátor má plné práva a môže používať všetky funkcie systému, vrátane zadá-
vania vlakov, pridávania nových šablón, úpravy a mazania šablón, zmeny stavu vlakov
a vagónov, pridávania poznámok a prístupu k štatistikám.
3.2.3 Bežný používateľ má obmedzené práva, ktoré zahŕňajú prezeranie naplánovaných vla-
kov, pridávanie poznámok a prístup k štatistikám.
3.3 Udržiavané dáta
3.3.1 Softvér udržiava vytvorené šablóny vlakov.
3.3.2 Šablóny obsahujú: meno (string), maximálnu dĺžku v metroch (integer) a destináciu
(string).
3.3.3 Softvér udržiava zadané vlaky.
<< 3.3.4 ...
>> 3.3.4 Vlaky sú popísané nasledujúcimi atribútmi: meno vlaku, maximálna dĺžka v m, destinácia, reálna dĺžka v metroch (integer), počet vagónov (integer), colný status (boolean), poznámka (string) a jeho aktuálny stav, plánovaný dátum a čas odchodu. Okrem poznámky sú všetky atribúty povinné.
3.3.5 Vlaky prechádzajú rôznymi stavmi: naplánovaný, v príprave, pripravený, expedovaný
a zrušený.
5
3.3.6 Vagóny obsahujú: poznámku (string) a jeho aktuálny stav.
3.3.7 Možné stavy vagónov: nenaložený, nakladá sa, naložený.
3.4 Interakcia užívateľa so softvérom
3.4.1 Softvér obsahuje rozhranie na vytváranie nových a editáciu už existujúcich šablón
vlakov.
<< 3.4.2 Softvér obsahuje rozhranie, v ktorom administrátor zadáva nové vlaky na konkrétny
dátum.
>> 3.4.2 Softvér obsahuje rozhranie, v ktorom administrátor zadáva nové vlaky.
3.4.3 Softvér obsahuje rozhranie (náhľad), v ktorom sa zobrazujú vlaky naplánované na
odchod v budúcnosti.
<<3.4.4 Informácie zobrazené o vlakoch v náhľade: presný čas odchodu, colný status, meno a
stav vlaku.
>>3.4.4 Informácie zobrazené o vlakoch v náhľade: presný čas odchodu, colný status, meno a
stav vlaku a súhrnná informácia o stavoch vagónov nenaložených/nakladaných/naložených.
3.4.5 Administrátor má možnosť aktualizovať stavy jednotlivých vlakov, bežný používateľ
nie.
3.4.6 Ku každému vlaku je možné pridávať poznámky.
3.4.7 Pri výbere konkrétneho vlaku sa zobrazí detailný zoznam všetkých priradených vagónov
a všetkých informácií o vlaku.
<<3.4.8 Pokiaľ vlak nie je expedovaný alebo zrušený, používatelia majú možnosť pridávať nové
vagóny alebo odoberať existujúce vagóny.
>>3.4.8 Pokiaľ vlak nie je expedovaný alebo zrušený, admin má možnosť pridávať nové
vagóny alebo odoberať existujúce vagóny.
3.4.9 Administrátor má možnosť aktualizovať stavy jednotlivých vagónov.
3.4.10 Ku každému vagónu je možné pridávať poznámky.
3.4.11 Softvér obsahuje osobitnú sekciu (tabuľa), do ktorej všetci užívatelia môžu pridávať
poznámky, ktoré vidia všetci užívatelia.
<<3.4.12 Poznámky v tabuli sa dajú zvýrazniť. Poznámku z tabule môžu odstrániť administrá-
tori alebo užívateľ, ktorý ju vytvoril.
>>3.4.12 Poznámky v tabuli sa dajú zvýrazniť. 
>>3.4.13 Poznámku z tabule môžu odstrániť administrátori alebo užívateľ, ktorý ju vytvoril.
6
3.5 Štatistika a analýza dát
3.5.1 Softvér udržiava informácie o vlakoch za účelom štatistiky.
<<3.5.2 Štatistiky sú filtrovateľné podľa rôznych kritérií, časových období a stavov vlakov.
>>3.5.2 Štatistiky sú AKO??? filtrovateľné podľa rôznych kritérií, časových období a stavov vlakov.
3.5.3 Softvér umožňuje export dát do formátu Power BI.

**Comment by adrkoc** [comment]
zmeny upravene, finálna verzia, veci ohľadom Power Bi sa ešte riešia, nedali nám vedieť ale inak všetko by malo byť 

[Katalóg požiadaviek final.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13216640/Katalog.poziadaviek.final.pdf)

**Comment by adrkoc** [comment]
ešte menšia zmena kvôli gramatickým chybám 

[finálny katalóg požiadaviek.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13216741/finalny.katalog.poziadaviek.pdf)

**Comment by adrkoc** [comment]
úprava katalógu na základe stretnutia so zadávateľom (prezentácia UI), boli veľké zmeny preto bol upravovaný (upravoval som ja a Michael)

[katalog uprava.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13485491/katalog.uprava.pdf)
