### ISSUE TITLE
Návrh používateľského rozhrania

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#5]
- [x] Vytvorit mockupy
- [x] Ukazat a komunikovat zmeny na stretnuti
- [ ] Dohodnut prezentaciu zadavatelom
- [ ] Schvalene zadavatelom

**Comment by adrkoc** [comment]
vytvorený mockup

[gui.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13280394/gui.pdf)

treba ešte prediskutovať na stretnutí

**Comment by adrkoc** [comment]
trochu updatnuté UI spolu s popisom a otázkami pri prezentácií zadávateľovi


[návrh použivateľkého rozhrania.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13332640/navrh.pouzivatelkeho.rozhrania.pdf)
