### ISSUE TITLE
Skompletizovat Navrh

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#6]
Zobrat uz vsetky dokoncene casti navrhu, dat ich do kopy a skompletizovat navrch.
Ma predpoklady: 
- [x] #5 
- [x] #7  
- [x] #8  
- [x] #9
- [x] #14 
- [x] #21 
- [x] Kompletne

**Comment by Pia669** [comment]
Ma predpoklady: 
#5 
#7  
#8  
#9
#14

**Comment by adrkoc** [comment]
začal som s dokumentom, urobil som len úvod a rozdelil dokument na jednotlivé časti, ďalšie veci budem pridávať keď sa skompletizujú, hlavne po stretnutí so zadávateľom



[návrh systému.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13336765/navrh.systemu.pdf)

**Comment by adrkoc** [comment]
update návrhu, dplnil som používateľské prostredie s popisom na základe stretnutia so zadávateľom, ostatné časti, ktoré sú dokončené dopridávam v priebehu týždňa 


[navrh uprava.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13426660/navrh.uprava.pdf)

**Comment by adrkoc** [comment]
skoro dokončený návrh, už chýbajú len veci, na ktoré čakáme



[návrh úprava.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13488565/navrh.uprava.pdf)

**Comment by adrkoc** [comment]
[návrh úprava.pdf](https://github.com/TIS2023-FMFI/vlaky/files/13560940/navrh.uprava.pdf)
