### ISSUE TITLE
podrobná špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by Pia669** [TIS2023-FMFI/vlaky#7]
- [x] export/archivacia udajov z databazy
- [x] mail service

**Comment by Pia669** [comment]
priklad exportovanej historie a archyvou

[priklad.csv](https://github.com/TIS2023-FMFI/vlaky/files/13395624/priklad.csv)

**Comment by jakino22** [comment]
using System;

using MailKit.Net.Smtp;
using MailKit;
using MimeKit;

namespace TestClient {
  class Program
  {
    public static void Main (string[] args)
    {
      var email = new MimeMessage();

      email.From.Add(new MailboxAddress("Sender Name", "01michael.j@gmail.com"));
      email.To.Add(new MailboxAddress("Receiver Name", "bublavy3@uniba.sk"));

      email.Subject = "Testing out email sending";
      email.Body = new TextPart(MimeKit.Text.TextFormat.Html) { 
        Text = "<b>Hello all the way from the land of C#</b>"
      };

      using (var smtp = new SmtpClient())
      {
        

        // Note: only needed if the SMTP server requires authentication
        

            smtp.Connect("smtp.gmail.com", 587, false);
            smtp.Authenticate("01michael.j@gmail.com", "szeo roag urep iftt");
            smtp.Send(email);
            smtp.Disconnect(true);

        
      }
    }
  }
}
