### ISSUE TITLE
nacitanie dat z template fix

### ISSUE THREAD

**Issue by jakino22** [TIS2023-FMFI/vlaky#81]

**Comment by jakino22** [comment]
teraz sa data automaticky nacitaju z vybraneho templatu

**Comment by adrkoc** [comment]
-> po zakliknutí templatu sa automaticky vyplnia dané políčka, pri ukladaní templatu sa overí či už taký template neexistuje, ak nie tak sa uloží inak nie

-> zakliknutie templatu automaticky bralo názov a destináciu z templatu aj po prepísaní názvu alebo destinácie -> fixed
